# Generated by Django 4.2.7 on 2023-12-13 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0004_productadd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductAdd',
        ),
    ]
