# Generated by Django 4.2.7 on 2023-12-13 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additems',
            old_name='price',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='additems',
            old_name='description',
            new_name='brief',
        ),
        migrations.RenameField(
            model_name='additems',
            old_name='image',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='additems',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterModelTable(
            name='additems',
            table='add_items',
        ),
    ]
