# Generated by Django 4.2.7 on 2023-12-13 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0003_alter_additems_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='additems',
            table='grocery_items',
        ),
    ]
