# Generated by Django 4.2.7 on 2023-12-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproducts',
            name='status',
            field=models.TextField(null=True),
        ),
    ]
