# Generated by Django 4.2.7 on 2023-12-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_addproducts_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproducts',
            name='image',
        ),
        migrations.AddField(
            model_name='addproducts',
            name='img',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
